# Importing Libiraies

In [1]:
import pandas as pd
import matplotlib.pyplot as pt
import seaborn as sb
import plotly.express as plt

In [3]:
df=pd.read_csv('student_depression_dataset.csv')

In [5]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,'5-6 hours',Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,'5-6 hours',Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,'Less than 5 hours',Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,'7-8 hours',Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,'5-6 hours',Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,'5-6 hours',Unhealthy,'Class 12',Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,'Less than 5 hours',Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,'5-6 hours',Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,'Less than 5 hours',Healthy,'Class 12',Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,'Less than 5 hours',Healthy,BCA,Yes,2.0,3.0,Yes,1

In [ ]:
df.info()

In [ ]:
df[df['Profession']!="Student"]

# Rows Cleaning

In [7]:
df["Profession"] = df["Profession"].str.replace("'", "", regex=False)

In [9]:
df[df['Profession']!="Student"]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
113,609,Male,21.0,Ahmedabad,Civil Engineer,5.0,0.0,7.83,1.0,0.0,'5-6 hours',Healthy,MSc,Yes,11.0,3.0,Yes,1
422,2105,Female,31.0,Vadodara,Architect,5.0,0.0,6.95,3.0,0.0,'Less than 5 hours',Moderate,BSc,No,8.0,1.0,Yes,1
1845,9483,Female,32.0,Kalyan,UX/UI Designer,3.0,0.0,9.60,2.0,0.0,'7-8 hours',Moderate,PhD,Yes,5.0,3.0,No,1
2249,11470,Female,28.0,Ahmedabad,Digital Marketer,5.0,0.0,9.72,3.0,0.0,'More than 8 hours',Healthy,MA,Yes,10.0,5.0,Yes,1
2440,12425,Male,25.0,Kalyan,Content Writer,5.0,0.0,8.50,2.0,0.0,'5-6 hours',Moderate,B.Ed,Yes,0.0,2.0,Yes,1
3220,16196,Male,33.0,Jaipur,Architect,2.0,0.0,7.13,4.0,0.0,'More than 8 hours',Moderate,MSc,No,2.0,5.0,Yes,1
3388,16959,Female,24.0,Mumbai,Architect,3.0,0.0,8.89,5.0,0.0,'More than 8 hours',Unhealthy,MSc,Yes,3.0,5.0,Yes,1
3639,18291,Male,32.0,Agra,Educational Consultant,3.0,0.0,5.74,4.0,0.0,'7-8 hours',Healthy,B.Ed,Yes,3.0,5.0,Yes,1
3841,19226,Male,31.0,Rajkot,Teacher,3.0,0.0,7.48,5.0,0.0,'5-6 hours',Unhealthy,MD,Yes,12.0,2.0,Yes,1
5016,25193,Male,24.0,Kalyan,Teacher,4.0,0.0,9.66,5.0,0.0,'7-8 hours',Moderate,BE,Yes,12.0,3.0,No,1
8537,43035,Male,23.0,Patna,Manager,3.0,0.0,8.62,2.0,0.0,'More than 8 hours',Healthy,BHM,No,9.0,5.0,No,1
12124,61219,Female,23.0,Kalyan,Chef,3.0,0.0,9.91,4.0,0.0,'7-8 hours',Healthy,BHM,Yes,10.0,3.0,No,1
12350,62410,Female,34.0,Ghaziabad,Content Writer,5.0,0.0,6.83,4.0,0.0,'7-8 hours',Moderate,MA,Yes,5.0,5.0,No,1
14352,72541,Female,28.0,Hyderabad,Architect,3.0,0.0,6.99,3.0,0.0,'5-6 hours',Moderate,BSc,Yes,10.0,5.0,Yes,1
15472,78083,Male,32.0,Meerut,Doctor,5.0,0.0,9.70,3.0,0.0,'Less than 5 hours',Healthy,M.Pharm,Yes,3.0,4.0,No,1
16108,81442,Male,23.0,Kanpur,Lawyer,4.0,0.0,6.88,1.0,0.0,'More than 8 hours',Unhealthy,LLM,Yes,2.0,4.0,No,1
17550,88879,Female,29.0,Agra,Chef,2.0,0.0,6.86,3.0,0.0,'7-8 hours',Moderate,BHM,Yes,12.0,4.0,Yes,1
17585,89052,Female,29.0,Meerut,Doctor,3.0,0.0,6.35,3.0,0.0,'Less than 5 hours',Healthy,MD,No,12.0,1.0,No,1
18213,92226,Male,26.0,Bhopal,Architect,4.0,0.0,7.28,3.0,0.0,'More than 8 hours',Healthy,BSc,No,12.0,4.0,Yes,0
20568,104123,Male,28.0,Ludhiana,Digital Marketer,1.0,0.0,9.41,5.0,0.0,'5-6 hours',Healthy,BA,Yes,5.0,3.0,Yes,0
20801,105237,Female,21.0,Chennai,Entrepreneur,3.0,0.0,8.17,5.0,0.0,'Less than 5 hours',Moderate,MCA,Yes,4.0,3.0,No,1
20872,105595,Male,28.0,Jaipur,Teacher,3.0,0.0,5.82,4.0,0.0,'5-6 hours',Moderate,MD,Yes,5.0,1.0,No,0
22178,111939,Male,24.0,Bangalore,Architect,5.0,0.0,7.09,4.0,0.0,'Less than 5 hours',Unhealthy,BBA,Yes,1.0,3.0,Yes,1
24121,121474,Male,27.0,Kalyan,Teacher,3.0,0.0,5.89,3.0,0.0,'Less than 5 hours',Unhealthy,MSc,Yes,2.0,5.0,No,1
24482,123259,Male,23.0,Kanpur,Teacher,3.0,0.0,5.59,1.0,0.0,'More than 8 hours',Healthy,BCA,Yes,11.0,4.0,Yes,1
25219,127070,Male,32.0,Meerut,Pharmacist,4.0,0.0,8.54,1.0,0.0,'7-8 hours',Unhealthy,MBBS,Yes,2.0,5.0,Yes,1
25335,127637,Female,25.0,Delhi,Architect,5.0,0.0,8.98,3.0,0.0,'More than 8 hours',Healthy,B.Arch,Yes,5.0,5.0,No,1
25689,129499,Female,21.0,Kalyan,Digital Marketer,5.0,0.0,6.91,4.0,0.0,'Less than 5 hours',Moderate,M.Com,No,10.0,5.0,No,1
26289,132550,Male,25.0,Visakhapatnam,Teacher,5.0,0.0,7.25,1.0,0.0,'7-8 hours',Unhealthy,B.Ed,Yes,1.0,1.0,Yes,1
27109,136642,Male,29.0,Ludhiana,Pharmacist,4.0,0.0,5.77,4.0,0.0,'More than 8 hours',Healthy,B.Pharm,Yes,4.0,2.0,No,1
27873,140522,Female,22.0,Vasai-Virar,Architect,3.0,0.0,9.13,4.0,0.0,'7-8 hours',Unhealthy,MCA,Yes,4.0,1.0,Yes,1

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  object
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  object
 4   Profession                             27901 non-null  object
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  object
 11  Dietary Habits                         27901 non-null  object
 12  Degree                                 27901 non-null  object
 13  Have you ever had suicidal thoughts ?  27901 non-null  object
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27901 non-null  object
 16  Family History of Mental Illness       27901 non-null  object
 17  Depression                             27901 non-null  int64
dtypes: float64(7), int64(2), object(9)
memory usage: 3.8+ MB

Profession to Acadimic Pressure

In [ ]:
pt.figure(figsize=(10,10))
pt.bar(df['Profession'], df['Academic Pressure'])
pt.ylabel("Academic Pressure")
pt.xlabel("Profession")
pt.title("Profession to Academic pressure")
pt.xticks(rotation=90)
pt.legend()
pt.show()

# Profession to Work Pressure

In [ ]:
pt.figure(figsize=(10,10))
pt.bar(df['Profession'], df['Work Pressure'])
pt.ylabel("Work Pressure")
pt.xlabel("Profession")
pt.title("Profession to Work pressure")
pt.xticks(rotation=90)
pt.legend()
pt.show()

# Profession to study Satisifaction

In [ ]:
pt.figure(figsize=(10,10))
pt.bar(df['Profession'], df['Study Satisfaction'])
pt.ylabel("Study Satisfaction")
pt.xlabel("Profession")
pt.title("Profession to Study Satisfaction")
pt.xticks(rotation=90)
pt.legend()
pt.show()

# Profession to Job satisfaction

In [ ]:
pt.figure(figsize=(10,10))
pt.bar(df['Profession'], df['Job Satisfaction'])
pt.ylabel("Job Satisfaction")
pt.xlabel("Profession")
pt.title("Profession to Job Satisfaction")
pt.xticks(rotation=90)
pt.legend()
pt.show()

# Profession To Financial strees

There were missing values in the financial strees 
so the mean of values offinancial strees were modified in 3 rows

In [8]:
df['Financial Stress'].unique()

array(['1.0', '2.0', '5.0', '3.0', '4.0', '?'], dtype=object)

In [11]:
df[df['Financial Stress']=="?"]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
4458,22377,Female,32.0,Varanasi,Student,3.0,0.0,5.64,1.0,0.0,'5-6 hours',Healthy,BCA,No,12.0,?,No,1
13596,68910,Male,29.0,Hyderabad,Student,2.0,0.0,8.94,3.0,0.0,'Less than 5 hours',Unhealthy,B.Ed,No,12.0,?,Yes,0
19266,97610,Female,20.0,Kolkata,Student,1.0,0.0,6.83,1.0,0.0,'5-6 hours',Healthy,MBBS,No,9.0,?,Yes,0

In [13]:
# Change the profession of the person in row 4458
df.loc[4458	, "Financial Stress"] = "3.0"
# Change the profession of the person in row 13596
df.loc[13596, "Financial Stress"] = "3.0"
# Change the profession of the person in row 19266
df.loc[19266, "Financial Stress"] = "3.0"

In [ ]:
students=df[df['Profession']=="Student"]

In [ ]:
pt.figure(figsize=(14, 8))
sb.countplot(data=df, x='Profession', hue='Financial Stress')
pt.title('Students to Financial Presentation')
pt.ylabel('Count')
pt.xlabel('Profession')
pt.xticks(rotation=90)
pt.tight_layout()

pt.show()

# Financial Stress Student

In [ ]:
pt.figure(figsize=(14, 8))
ax=sb.countplot(data=students, x='Profession', hue='Financial Stress')
pt.title('Students to Financial Presentation')
pt.ylabel('Count')
pt.xlabel('Profession')
pt.xticks(rotation=90)
pt.tight_layout()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

# Financial stress non students

In [17]:
non_stud=df[df['Profession']!="Student"]

In [ ]:
non_stud['Financial Stress'].unique()

In [ ]:
non_stud['Financial Stress'] = non_stud['Financial Stress'].astype(str).str.strip().str.replace("'", "", regex=False)
non_stud['Financial Stress']=non_stud['Financial Stress'].astype(float)

In [ ]:
non_stud['Financial Stress'].dtype

In [ ]:
len(non_stud)

In [ ]:
pt.figure(figsize=(14, 8))
sb.countplot(data=non_stud, x='Profession', hue='Financial Stress')
pt.title('Non-Student Profession to Financail Stress Presentation')
pt.ylabel('Count')
pt.xlabel('Profession')
pt.xticks(rotation=90)
pt.yticks()
pt.tight_layout()
pt.show()

In [ ]:
len(df[df['Profession']=="Architect"])

In [ ]:
pt.figure(figsize=(8, 6))
ax=sb.countplot(data=students, x='Profession', hue='Family History of Mental Illness')
pt.title('Student to Family illenst history Presentation')
pt.ylabel('Count')
pt.xlabel('Profession')
pt.xticks(rotation=90)
pt.tight_layout()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

In [ ]:
pt.figure(figsize=(8, 6))
ax=sb.countplot(data=non_stud, x='Profession', hue='Family History of Mental Illness')
pt.title('Non-Student Profession to Family illenst history Presentation')
pt.ylabel('Count')
pt.xlabel('Profession')
pt.xticks(rotation=90)
pt.tight_layout()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

In [ ]:
pt.figure(figsize=(10, 6))
ax=sb.countplot(data=students, x='Profession', hue='Have you ever had suicidal thoughts ?')
pt.title('Students vs Have you ever had suicidal thoughts ?	')
pt.xticks(rotation=90)
pt.tight_layout()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

# Suicidal Thoughts non Student

In [ ]:
pt.figure(figsize=(10, 6))
ax=sb.countplot(data=non_stud, x='Profession', hue='Have you ever had suicidal thoughts ?')
pt.title('Non-Student Profession vs Have you ever had suicidal thoughts ?	')
pt.xticks(rotation=90)
pt.tight_layout()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

# Students sleep Duration

In [ ]:
pt.figure(figsize=(10, 6))
ax=sb.countplot(data=students, x='Profession', hue='Sleep Duration')
pt.title('Students vs Sleep duration')
pt.xticks(rotation=90)
pt.tight_layout()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

# Non Students vs sleep duration

In [ ]:
pt.figure(figsize=(10, 6))
ax=sb.countplot(data=non_stud, x='Profession', hue='Sleep Duration')
pt.title('Students vs Sleep duration')
pt.xticks(rotation=90)
pt.tight_layout()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

In [ ]:
pt.figure(figsize=(10, 6))
ax=sb.countplot(data=students, x='Profession', hue='Dietary Habits')
pt.title('Students vs Dietary Habits')
pt.xticks(rotation=90)
pt.tight_layout()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

In [ ]:
pt.figure(figsize=(10, 6))
ax=sb.countplot(data=non_stud, x='Profession', hue='Dietary Habits')
pt.title('Non students Profession vs Dietary Habits')
pt.xticks(rotation=90)
pt.tight_layout()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

# Student depression

In [ ]:
pt.figure(figsize=(10, 6))
ax=sb.countplot(data=students, x='Profession', hue='Depression')
pt.title('Students vs Dietary Habits')
pt.xticks(rotation=90)
pt.tight_layout()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

# Non student depression

In [ ]:
pt.figure(figsize=(10, 6))
ax=sb.countplot(data=non_stud, x='Profession', hue='Depression')
pt.title('Students vs Dietary Habits')
pt.xticks(rotation=90)
pt.tight_layout()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

# CGPA histplot

In [ ]:
ax=sb.histplot(data=students,x='CGPA',bins=30,kde=True, hue='Profession')
pt.title('CGPA Histplot')
pt.show()

In [ ]:
pt.figure(figsize=(12,12))
ax=sb.histplot(data=non_stud,x='CGPA',bins=30,kde=False, hue='Profession')
pt.title('CGPA Histplot')
pt.show()

# Age histo

In [ ]:
pt.figure(figsize=(12,12))
ax=sb.histplot(data=students,x='Age',bins=30,kde=False, hue='Profession')
pt.title('Age Students Histplot')
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}', 
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='bottom', fontsize=8, rotation=0)
pt.show()

In [ ]:
sb.boxplot(data=non_stud,x='Profession',y='Age')
pt.xticks(rotation=90)
pt.title('Age to Distribu')

In [ ]:
with pd.ExcelWriter("Analysis Data Mod.xlsx") as writer:
    df.to_excel(writer,sheet_name='Student',index=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  object
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  object
 4   Profession                             27901 non-null  object
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  object
 11  Dietary Habits                         27901 non-null  object
 12  Degree                                 27901 non-null  object
 13  Have you ever had suicidal thoughts ?  27901 non-null  object
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27901 non-null  object
 16  Family History of Mental Illness       27901 non-null  object
 17  Depression                             27901 non-null  int64
dtypes: float64(7), int64(2), object(9)
memory usage: 3.8+ MB

In [19]:
non_stud

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
113,609,Male,21.0,Ahmedabad,Civil Engineer,5.0,0.0,7.83,1.0,0.0,'5-6 hours',Healthy,MSc,Yes,11.0,3.0,Yes,1
422,2105,Female,31.0,Vadodara,Architect,5.0,0.0,6.95,3.0,0.0,'Less than 5 hours',Moderate,BSc,No,8.0,1.0,Yes,1
1845,9483,Female,32.0,Kalyan,UX/UI Designer,3.0,0.0,9.60,2.0,0.0,'7-8 hours',Moderate,PhD,Yes,5.0,3.0,No,1
2249,11470,Female,28.0,Ahmedabad,Digital Marketer,5.0,0.0,9.72,3.0,0.0,'More than 8 hours',Healthy,MA,Yes,10.0,5.0,Yes,1
2440,12425,Male,25.0,Kalyan,Content Writer,5.0,0.0,8.50,2.0,0.0,'5-6 hours',Moderate,B.Ed,Yes,0.0,2.0,Yes,1
3220,16196,Male,33.0,Jaipur,Architect,2.0,0.0,7.13,4.0,0.0,'More than 8 hours',Moderate,MSc,No,2.0,5.0,Yes,1
3388,16959,Female,24.0,Mumbai,Architect,3.0,0.0,8.89,5.0,0.0,'More than 8 hours',Unhealthy,MSc,Yes,3.0,5.0,Yes,1
3639,18291,Male,32.0,Agra,Educational Consultant,3.0,0.0,5.74,4.0,0.0,'7-8 hours',Healthy,B.Ed,Yes,3.0,5.0,Yes,1
3841,19226,Male,31.0,Rajkot,Teacher,3.0,0.0,7.48,5.0,0.0,'5-6 hours',Unhealthy,MD,Yes,12.0,2.0,Yes,1
5016,25193,Male,24.0,Kalyan,Teacher,4.0,0.0,9.66,5.0,0.0,'7-8 hours',Moderate,BE,Yes,12.0,3.0,No,1
8537,43035,Male,23.0,Patna,Manager,3.0,0.0,8.62,2.0,0.0,'More than 8 hours',Healthy,BHM,No,9.0,5.0,No,1
12124,61219,Female,23.0,Kalyan,Chef,3.0,0.0,9.91,4.0,0.0,'7-8 hours',Healthy,BHM,Yes,10.0,3.0,No,1
12350,62410,Female,34.0,Ghaziabad,Content Writer,5.0,0.0,6.83,4.0,0.0,'7-8 hours',Moderate,MA,Yes,5.0,5.0,No,1
14352,72541,Female,28.0,Hyderabad,Architect,3.0,0.0,6.99,3.0,0.0,'5-6 hours',Moderate,BSc,Yes,10.0,5.0,Yes,1
15472,78083,Male,32.0,Meerut,Doctor,5.0,0.0,9.70,3.0,0.0,'Less than 5 hours',Healthy,M.Pharm,Yes,3.0,4.0,No,1
16108,81442,Male,23.0,Kanpur,Lawyer,4.0,0.0,6.88,1.0,0.0,'More than 8 hours',Unhealthy,LLM,Yes,2.0,4.0,No,1
17550,88879,Female,29.0,Agra,Chef,2.0,0.0,6.86,3.0,0.0,'7-8 hours',Moderate,BHM,Yes,12.0,4.0,Yes,1
17585,89052,Female,29.0,Meerut,Doctor,3.0,0.0,6.35,3.0,0.0,'Less than 5 hours',Healthy,MD,No,12.0,1.0,No,1
18213,92226,Male,26.0,Bhopal,Architect,4.0,0.0,7.28,3.0,0.0,'More than 8 hours',Healthy,BSc,No,12.0,4.0,Yes,0
20568,104123,Male,28.0,Ludhiana,Digital Marketer,1.0,0.0,9.41,5.0,0.0,'5-6 hours',Healthy,BA,Yes,5.0,3.0,Yes,0
20801,105237,Female,21.0,Chennai,Entrepreneur,3.0,0.0,8.17,5.0,0.0,'Less than 5 hours',Moderate,MCA,Yes,4.0,3.0,No,1
20872,105595,Male,28.0,Jaipur,Teacher,3.0,0.0,5.82,4.0,0.0,'5-6 hours',Moderate,MD,Yes,5.0,1.0,No,0
22178,111939,Male,24.0,Bangalore,Architect,5.0,0.0,7.09,4.0,0.0,'Less than 5 hours',Unhealthy,BBA,Yes,1.0,3.0,Yes,1
24121,121474,Male,27.0,Kalyan,Teacher,3.0,0.0,5.89,3.0,0.0,'Less than 5 hours',Unhealthy,MSc,Yes,2.0,5.0,No,1
24482,123259,Male,23.0,Kanpur,Teacher,3.0,0.0,5.59,1.0,0.0,'More than 8 hours',Healthy,BCA,Yes,11.0,4.0,Yes,1
25219,127070,Male,32.0,Meerut,Pharmacist,4.0,0.0,8.54,1.0,0.0,'7-8 hours',Unhealthy,MBBS,Yes,2.0,5.0,Yes,1
25335,127637,Female,25.0,Delhi,Architect,5.0,0.0,8.98,3.0,0.0,'More than 8 hours',Healthy,B.Arch,Yes,5.0,5.0,No,1
25689,129499,Female,21.0,Kalyan,Digital Marketer,5.0,0.0,6.91,4.0,0.0,'Less than 5 hours',Moderate,M.Com,No,10.0,5.0,No,1
26289,132550,Male,25.0,Visakhapatnam,Teacher,5.0,0.0,7.25,1.0,0.0,'7-8 hours',Unhealthy,B.Ed,Yes,1.0,1.0,Yes,1
27109,136642,Male,29.0,Ludhiana,Pharmacist,4.0,0.0,5.77,4.0,0.0,'More than 8 hours',Healthy,B.Pharm,Yes,4.0,2.0,No,1
27873,140522,Female,22.0,Vasai-Virar,Architect,3.0,0.0,9.13,4.0,0.0,'7-8 hours',Unhealthy,MCA,Yes,4.0,1.0,Yes,1

In [ ]:
with pd.ExcelWriter("StudentDepDS.xlsx") as writer:
    df.to_excel(writer,sheet_name='Student',index=True)
    non_stud.to_excel(writer,sheet_name='Non-studnet',index=True)